
services:
  dhalugueis-app:
    # Constrói a imagem Docker usando o Dockerfile no diretório atual.
    build: .
    # Nomeia o container para facilitar o gerenciamento.
    container_name: dhalugueis_container
    # Mapeia a porta 8094 da máquina host para a porta 3000 dentro do container.
    ports:
      - "8094:3000"
    # Este é o ponto mais importante para a persistência de dados.
    # Ele mapeia a pasta `./data` do seu projeto no host para a pasta `/app/data` dentro do container.
    # TUDO dentro desta pasta, incluindo o banco de dados (dhalugueis.db) e quaisquer uploads futuros,
    # será salvo diretamente no seu computador, sobrevivendo a reinicializações ou recriações do container.
    volumes:
      - ./data:/app/data
    # Esta linha instrui o Docker a carregar as variáveis de ambiente do arquivo .env
    # para que a aplicação dentro do container possa acessá-las (ex: credenciais de email).
    env_file:
      - .env
    # Reinicia o container automaticamente se ele travar, a menos que tenha sido parado manualmente.
    restart: unless-stopped
    environment:
      # Garante que o Next.js seja executado em modo de produção dentro do container.
      - NODE_ENV=production
